// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl9i67Nu4R8Al9exV76w9cf_YsZCg65QY',
    appId: '1:1058316484956:web:7c26f8c6b05b5278b28199',
    messagingSenderId: '1058316484956',
    projectId: 'fruit-hub-ad1b7',
    authDomain: 'fruit-hub-ad1b7.firebaseapp.com',
    storageBucket: 'fruit-hub-ad1b7.firebasestorage.app',
    measurementId: 'G-G6KP6N9LTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC4OrKjB6TdCgzQf5XmbEiTnQPXP2RK3g',
    appId: '1:1058316484956:android:d4e05429c7050e92b28199',
    messagingSenderId: '1058316484956',
    projectId: 'fruit-hub-ad1b7',
    storageBucket: 'fruit-hub-ad1b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJgAulhHzUJh9crHkYJ6LaYBk6tA10p_0',
    appId: '1:1058316484956:ios:42b26c142e50216fb28199',
    messagingSenderId: '1058316484956',
    projectId: 'fruit-hub-ad1b7',
    storageBucket: 'fruit-hub-ad1b7.firebasestorage.app',
    iosBundleId: 'com.example.fruitCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJgAulhHzUJh9crHkYJ6LaYBk6tA10p_0',
    appId: '1:1058316484956:ios:42b26c142e50216fb28199',
    messagingSenderId: '1058316484956',
    projectId: 'fruit-hub-ad1b7',
    storageBucket: 'fruit-hub-ad1b7.firebasestorage.app',
    iosBundleId: 'com.example.fruitCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl9i67Nu4R8Al9exV76w9cf_YsZCg65QY',
    appId: '1:1058316484956:web:5ef3158da18ebc29b28199',
    messagingSenderId: '1058316484956',
    projectId: 'fruit-hub-ad1b7',
    authDomain: 'fruit-hub-ad1b7.firebaseapp.com',
    storageBucket: 'fruit-hub-ad1b7.firebasestorage.app',
    measurementId: 'G-NRD058BE3P',
  );
}
